spring:
    application:
        name: zf-api-gate

server:
    port: 8765 #启动端口

jwt:
  token-header: Authorization
  expire: 3600
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: ${eureka.url1},${eureka.url2}
