spring:
    application:
        name: zf-api-gate

server:
    port: 8200 #启动端口

jwt:
  token-header: Authorization
  expire: 3600
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://192.168.0.31:7001/eureka/,http://192.168.0.31:7002/eureka/
