spring:
    application:
        name: zf-monitor
    boot:
        admin:
          routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
          turbine:
            clusters: jscloud
            location: turbine


server:
    port: 9700

security:
    user:
        name: xjh
        password: 123456
        role: USER

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:7000/eureka/