logging:
    level:
        tk.mybatis: DEBUG
        cn.derek.springcloud.learning.admin: DEBUG
spring:
    application:
        name: zf-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.6:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: fooltech
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: cn.derek.springcloud.learning.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 9500

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://192.168.0.31:7001/eureka/,http://192.168.0.31:7002/eureka/

management.security.enabled: false
