spring:
    application:
        name: zf-api-gate

server:
    port: 8765 #启动端口
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    config:
      path: /config-client/**
      serviceId: zf-config-client

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:7000/eureka/
