spring:
    application:
        name: zf-config-server
    cloud:
        config:
          label: master
          server:
            git:
              uri: https://github.com/aileensky/zf-config-repo/
              searchPaths: respo


server:
    port: 8000 #启动端口

eureka:
    client:
        service-url:
          defaultZone: http://localhost:7000/eureka